[git]
mainline-branch-name = 'main' # typically 'master' or 'main'
remote-name = 'origin'

# fixer command appropriate to your chosen language/tool
# e.g. for PHP, using php-cs-fixer:
# `./vendor/bin/php-cs-fixer fix ./src/ --rules=@PSR12`
[codingstandards]
command-to-run = './vendor/bin/php-cs-fixer'
command-args = ['fix', './src/', '--rules=@PSR12']
