[git]
mainline-branch-name = 'main' # typically 'master' or 'main'
remote-name = 'origin'

[codingstandards]
# fixer command appropriate to your chosen language/tool
command-to-run = './vendor/bin/php-cs-fixer fix ./src/ --rules=@PSR12'
